/*
 * generated by Xtext
 */
package de.fzi.sensidl.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.fzi.sensidl.language.ui.internal.SensidlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SensidlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SensidlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SensidlActivator.getInstance().getInjector(SensidlActivator.DE_FZI_SENSIDL_LANGUAGE_SENSIDL);
	}
	
}
