<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sensidl" nsURI="http://fzi.de/sensidl/design/1.0" nsPrefix="de.fzi.design.model.sensidl">
  <eClassifiers xsi:type="ecore:EClass" name="DataModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" ordered="false"
        upperBound="-1" eType="#//Representation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datafields" upperBound="-1"
        eType="#//Datafield" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transmit" lowerBound="1"
        upperBound="-1" eType="#//Datafield"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" ordered="false"
        lowerBound="1" eType="#//Options" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Representation" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteCount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datafield" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Calculated" eSuperTypes="#//Datafield">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representation" lowerBound="1"
        eType="#//Representation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodNameOut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datafield" lowerBound="1"
        eType="#//Datafield"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argumentType" lowerBound="1"
        eType="#//ArgumentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantData" eSuperTypes="#//Datafield">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representation" lowerBound="1"
        eType="#//Representation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasuredData" eSuperTypes="#//VariableData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//DataConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datastructure" eSuperTypes="#//Datafield">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datafields" upperBound="-1"
        eType="#//Datafield" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="BOOL"/>
    <eLiterals name="CHAR" value="1"/>
    <eLiterals name="SHORT" value="2"/>
    <eLiterals name="INT" value="3" literal="INT"/>
    <eLiterals name="LONG" value="4"/>
    <eLiterals name="LONGLONG" value="5" literal="LONGLONG"/>
    <eLiterals name="FLOAT" value="6" literal="FLOAT"/>
    <eLiterals name="DOUBLE" value="7"/>
    <eLiterals name="LONGDOUBLE" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArgumentType">
    <eLiterals name="BYTE_ARRAY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Options">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorLanguage" eType="#//GenerationLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiverLanguage" eType="#//GenerationLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endianess" eType="#//Endianess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GenerationLanguage">
    <eLiterals name="JAVA"/>
    <eLiterals name="CPP" value="1"/>
    <eLiterals name="C" value="2"/>
    <eLiterals name="CSHARP" value="3" literal="CSHARP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" interface="true"
      eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataConstraint" abstract="true" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataRange" eSuperTypes="#//DataConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBound" eType="#//Bound"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" eType="#//Bound"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bound">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataAdaption" eSuperTypes="#//DataConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scalingFactor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableData" abstract="true" eSuperTypes="#//Datafield">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representation" lowerBound="1"
        eType="#//Representation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonMeasuredData" eSuperTypes="#//VariableData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Endianess">
    <eLiterals name="BIG_ENDIAN"/>
    <eLiterals name="LITTLE_ENDIAN" value="1"/>
  </eClassifiers>
</ecore:EPackage>
