<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sensidl" nsURI="http://fzi.de/sensidl/design/1.0" nsPrefix="de.fzi.sensidl.design">
  <eClassifiers xsi:type="ecore:EClass" name="IdentifiableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribableElement" abstract="true"
      eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorInterface" eSuperTypes="#//NamedElement #//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="encodingSettings" lowerBound="1"
        eType="#//EncodingSettings" containment="true" eOpposite="#//EncodingSettings/sensorInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataDescription" lowerBound="1"
        eType="#//dataRepresentation/SensorDataDescription" containment="true" eOpposite="#//dataRepresentation/SensorDataDescription/sensorInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncodingSettings" eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensorInterface" lowerBound="1"
        eType="#//SensorInterface" eOpposite="#//SensorInterface/encodingSettings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coding" lowerBound="1"
        eType="#//Coding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endianness" lowerBound="1"
        eType="#//Endianness"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Coding">
    <eLiterals name="SENSIDL_BINARY"/>
    <eLiterals name="SENSIDL_JSON" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Endianness">
    <eLiterals name="BIG_ENDIAN"/>
    <eLiterals name="LITTLE_ENDIAN" value="1"/>
  </eClassifiers>
  <eSubpackages name="dataRepresentation" nsURI="http://fzi.de/sensidl/design/representation/1.0"
      nsPrefix="de.fzi.sensidl.design.sensidl">
    <eClassifiers xsi:type="ecore:EClass" name="SensorDataDescription" eSuperTypes="#//IdentifiableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataSets" upperBound="-1"
          eType="#//dataRepresentation/DataSet" containment="true" eOpposite="#//dataRepresentation/DataSet/sensorDataDescription"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensorInterface" lowerBound="1"
          eType="#//SensorInterface" eOpposite="#//SensorInterface/dataDescription"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataSet" eSuperTypes="#//NamedElement #//DescribableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensorDataDescription"
          eType="#//dataRepresentation/SensorDataDescription" eOpposite="#//dataRepresentation/SensorDataDescription/dataSets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subDataSets" upperBound="-1"
          eType="#//dataRepresentation/DataSet" containment="true" eOpposite="#//dataRepresentation/DataSet/parentDataSet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1"
          eType="#//dataRepresentation/Data" containment="true" eOpposite="#//dataRepresentation/Data/dataSet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentDataSet" eType="#//dataRepresentation/DataSet"
          eOpposite="#//dataRepresentation/DataSet/subDataSets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Data" abstract="true" eSuperTypes="#//NamedElement #//DescribableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataSet" eType="#//dataRepresentation/DataSet"
          eOpposite="#//dataRepresentation/DataSet/data"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
          eType="#//dataRepresentation/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MeasurementData" eSuperTypes="#//dataRepresentation/Data">
      <eStructuralFeatures xsi:type="ecore:EReference" name="adjustments" upperBound="-1"
          eType="#//dataRepresentation/DataAdjustment" containment="true" eOpposite="#//dataRepresentation/DataAdjustment/measurementData"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1">
        <eGenericType eClassifier="#//dataRepresentation/Unit">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NonMeasurementData" eSuperTypes="#//dataRepresentation/Data">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataAdjustment" abstract="true" eSuperTypes="#//IdentifiableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="measurementData" eType="#//dataRepresentation/MeasurementData"
          eOpposite="#//dataRepresentation/MeasurementData/adjustments"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataRange" eSuperTypes="#//dataRepresentation/DataAdjustment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1"
          eType="#//dataRepresentation/Interval" containment="true" eOpposite="#//dataRepresentation/Interval/dataRange"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataConversion" eSuperTypes="#//dataRepresentation/DataAdjustment"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinearDataConversion" eSuperTypes="#//dataRepresentation/DataConversion">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scalingFactor" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromInterval" eType="#//dataRepresentation/Interval"
          containment="true" eOpposite="#//dataRepresentation/Interval/linearDataConversionFrom"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toInterval" eType="#//dataRepresentation/Interval"
          containment="true" eOpposite="#//dataRepresentation/Interval/linearDataConversionTo"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DataType">
      <eLiterals name="SIGNED_CHAR"/>
      <eLiterals name="UNSIGNED_CHAR" value="1"/>
      <eLiterals name="SIGNED_SHORT" value="2"/>
      <eLiterals name="UNSIGNED_SHORT" value="3"/>
      <eLiterals name="SIGNED_LONG" value="4"/>
      <eLiterals name="UNSIGNED_LONG" value="5"/>
      <eLiterals name="SIGNED_LONG_LONG" value="6"/>
      <eLiterals name="UNSIGNED_LONG_LONG" value="7"/>
      <eLiterals name="FLOAT" value="8"/>
      <eLiterals name="DOUBLE" value="9"/>
      <eLiterals name="LONG_DOUBLE" value="10"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Unit" instanceClassName="javax.measure.unit.Unit">
      <eTypeParameters name="Q"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interval" eSuperTypes="#//IdentifiableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linearDataConversionFrom"
          eType="#//dataRepresentation/LinearDataConversion" eOpposite="#//dataRepresentation/LinearDataConversion/fromInterval"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linearDataConversionTo"
          eType="#//dataRepresentation/LinearDataConversion" eOpposite="#//dataRepresentation/LinearDataConversion/toInterval"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" eType="#//dataRepresentation/DataRange"
          eOpposite="#//dataRepresentation/DataRange/range"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
