<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sensidl" nsURI="http://fzi.de/sensidl/design/1.0" nsPrefix="de.fzi.sensidl.design">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorInterface" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" lowerBound="1"
        eType="#//SensorMetaInformation" containment="true" eOpposite="#//SensorMetaInformation/sensorInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataDescription" lowerBound="1"
        eType="#//dataRepresentation/SensorDataDescription" containment="true" eOpposite="#//dataRepresentation/SensorDataDescription/sensorInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTransmission" lowerBound="1"
        eType="#//dataTransmission/SensorDataTransmission" containment="true" eOpposite="#//dataTransmission/SensorDataTransmission/sensorInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorMetaInformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensorInterface" lowerBound="1"
        eType="#//SensorInterface" eOpposite="#//SensorInterface/metaInformation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coding" lowerBound="1"
        eType="#//Coding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endianness" lowerBound="1"
        eType="#//Endianness"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" lowerBound="1"
        eType="#//Alignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Coding">
    <eLiterals name="SENSIDL_BINARY"/>
    <eLiterals name="SENSIDL_JSON" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Endianness">
    <eLiterals name="BIG_ENDIAN"/>
    <eLiterals name="LITTLE_ENDIAN" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Alignment">
    <eLiterals name="_8BIT" literal="_8BIT"/>
    <eLiterals name="_16BIT" value="1"/>
    <eLiterals name="_32BIT" value="2"/>
    <eLiterals name="_64BIT" value="3"/>
  </eClassifiers>
  <eSubpackages name="dataRepresentation" nsURI="http://fzi.de/sensidl/design/representation/1.0"
      nsPrefix="de.fzi.sensidl.design.sensidl">
    <eClassifiers xsi:type="ecore:EClass" name="SensorDataDescription" eSuperTypes="#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sets" upperBound="-1"
          eType="#//dataRepresentation/DataSet" containment="true" eOpposite="#//dataRepresentation/DataSet/sensorDataDescription"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensorInterface" lowerBound="1"
          eType="#//SensorInterface" eOpposite="#//SensorInterface/dataDescription"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataSet" eSuperTypes="#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensorDataDescription"
          eType="#//dataRepresentation/SensorDataDescription" eOpposite="#//dataRepresentation/SensorDataDescription/sets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sets" upperBound="-1"
          eType="#//dataRepresentation/DataSet" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1"
          eType="#//dataRepresentation/Data" containment="true" eOpposite="#//dataRepresentation/Data/dataSet"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Data" abstract="true" eSuperTypes="#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataSet" eType="#//dataRepresentation/DataSet"
          eOpposite="#//dataRepresentation/DataSet/data"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
          eType="#//dataRepresentation/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MeasurementData" eSuperTypes="#//dataRepresentation/Data">
      <eStructuralFeatures xsi:type="ecore:EReference" name="adjustments" upperBound="-1"
          eType="#//dataRepresentation/DataAdjustment" containment="true" eOpposite="#//dataRepresentation/DataAdjustment/measurementData"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1">
        <eGenericType eClassifier="#//dataRepresentation/Unit">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NonMeasurementData" eSuperTypes="#//dataRepresentation/Data">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataAdjustment" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="measurementData" eType="#//dataRepresentation/MeasurementData"
          eOpposite="#//dataRepresentation/MeasurementData/adjustments"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataRange" eSuperTypes="#//dataRepresentation/DataAdjustment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBound" lowerBound="1"
          eType="#//dataRepresentation/Bound" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" lowerBound="1"
          eType="#//dataRepresentation/Bound" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bound">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataConversion" eSuperTypes="#//dataRepresentation/DataAdjustment"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinearDataConversion" eSuperTypes="#//dataRepresentation/DataConversion">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scalingFactor" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DataType">
      <eLiterals name="SIGNED_CHAR"/>
      <eLiterals name="UNSIGNED_CHAR" value="1"/>
      <eLiterals name="SIGNED_SHORT" value="2"/>
      <eLiterals name="UNSIGNED_SHORT" value="3"/>
      <eLiterals name="SIGNED_LONG" value="4"/>
      <eLiterals name="UNSIGNED_LONG" value="5"/>
      <eLiterals name="SIGNED_LONG_LONG" value="6"/>
      <eLiterals name="UNSIGNED_LONG_LONG" value="7"/>
      <eLiterals name="FLOAT" value="8"/>
      <eLiterals name="DOUBLE" value="9"/>
      <eLiterals name="LONG_DOUBLE" value="10"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Unit" instanceClassName="javax.measure.unit.Unit">
      <eTypeParameters name="Q"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="dataTransmission" nsURI="http://fzi.de/sensidl/design/transmission/1.0"
      nsPrefix="de.fzi.sensidl.design.sensidl">
    <eClassifiers xsi:type="ecore:EClass" name="SensorDataTransmission" eSuperTypes="#//NamedElement">
      <eOperations name="connect"/>
      <eOperations name="startMeasurement" eType="#//dataRepresentation/DataSet"/>
      <eOperations name="stopMeasurement" eType="#//dataRepresentation/DataSet"/>
      <eOperations name="pauseMeasurement" eType="#//dataRepresentation/DataSet"/>
      <eOperations name="send"/>
      <eOperations name="send">
        <eParameters name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensorInterface" lowerBound="1"
          eType="#//SensorInterface" eOpposite="#//SensorInterface/dataTransmission"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
