/*
 * generated by Xtext 2.20.0
 */
package de.fzi.sensidl.language.parser.antlr;

import com.google.inject.Inject;
import de.fzi.sensidl.language.parser.antlr.internal.InternalSensidlParser;
import de.fzi.sensidl.language.services.SensidlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SensidlParser extends AbstractAntlrParser {

	@Inject
	private SensidlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSensidlParser createParser(XtextTokenStream stream) {
		return new InternalSensidlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SensorInterface";
	}

	public SensidlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SensidlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
